In [1]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(min_df=1,binary=True) #instantiate the CountVectorizer class

corpus = [
 			'This is the first document.',
    		'This is the second second document.',
    		'And the third one name.',
			'Is this the first document?',
            'hello hello hello my name the name'
		]
vectorizer.fit(corpus) #tag and index
print(vectorizer.vocabulary_) #print the vocabulary dic
vector = vectorizer.transform(corpus) #transform each document into a word frequency vector
feature_name = vectorizer.get_feature_names() #generate corpus into a vocabulary list

print(vector.shape) #vector length: 12, K=5
print(type(vector)) #type: sparse vector
print (feature_name)
print(vector.toarray()) #transform sparse vector into numpy array
print (vector) #sparse vector 
print(vector.toarray().sum(axis=0)) #count each word' frequency in the corpus

{'this': 11, 'is': 4, 'the': 9, 'first': 2, 'document': 1, 'second': 8, 'and': 0, 'third': 10, 'one': 7, 'name': 6, 'hello': 3, 'my': 5}
(5, 12)
<class 'scipy.sparse.csr.csr_matrix'>
['and', 'document', 'first', 'hello', 'is', 'my', 'name', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 0 1 0 0 0 0 1 0 1]
 [0 1 0 0 1 0 0 0 1 1 0 1]
 [1 0 0 0 0 0 1 1 0 1 1 0]
 [0 1 1 0 1 0 0 0 0 1 0 1]
 [0 0 0 1 0 1 1 0 0 1 0 0]]
  (0, 1)	1
  (0, 2)	1
  (0, 4)	1
  (0, 9)	1
  (0, 11)	1
  (1, 1)	1
  (1, 4)	1
  (1, 8)	1
  (1, 9)	1
  (1, 11)	1
  (2, 0)	1
  (2, 6)	1
  (2, 7)	1
  (2, 9)	1
  (2, 10)	1
  (3, 1)	1
  (3, 2)	1
  (3, 4)	1
  (3, 9)	1
  (3, 11)	1
  (4, 3)	1
  (4, 5)	1
  (4, 6)	1
  (4, 9)	1
[1 3 2 1 3 1 2 1 1 5 1 3]
